sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  allow_failures:
    - php: hhvm

before_script:
  - make

script:
    - make test
